spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flash_coupon
    username: coupon_user
    password: coupon_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: never

jwt:
  secret: this-is-a-very-long-secret-key-for-jwt-signature-32bytes
  expiration: 3600000